macroquest/macroquest

- src/main/datatypes/MQ2SpellType.cpp
Recent StacksPet change made it so that on the first stackable buff the function would exit with a value of TRUE.  Preventing a check of any other buffs the pet may have.
This change modifies the function somewhat back to how it was, while keeping the spirit of the previous change making duration check ignored with a 0 argument.  Also hopefully comments to clarify what is going on.
> Fixes issue with StacksPet

- src/main/datatypes/MQ2SpellType.cpp
WillLandPet was set up to return the slot number of the first blocking buff, if no buffs are preventing a spell land it would return 0.  WillLand logic is set up to return the slot number the spell would land in, otherwise 0 for wont land (blocking buff or slots full).
This change modifies WillLandPet to return 0 it a buff that will block the spell from landing is detected, or if the buff slots are full.  Otherwise returns the slot number of the first empty slot it finds.
> Fixes WillLandPet to match WillLand Behaviour

- data/resources/CHANGELOG.md
- src/plugins/lua/LuaCoroutine.cpp
- src/plugins/lua/LuaCoroutine.h
- src/plugins/lua/LuaThread.cpp
Update Lua `mq.delay` function to error if a string argument is provided with no time unit.
Example:
```
> /lua run delay
Running lua script 'delay' with PID 1
start
e:/git/macroquest/lua\delay.lua:4: Units are required when passing delay as a string.
stack traceback:
[C]: in function 'delay'
e:/git/macroquest/lua\delay.lua:4: in main chunk
Ending lua script 'delay' with PID 1 and status 2
```
> Prevent delay strings with no units in lua (#566)

- src/main/MQ2Utilities.cpp
Somewhat Corrects Issue #561
From the recent patch that changed Body Types around it seems Aura and other Aura like abilities got changed around as well.
I have limited access to a variety of Aura but from what I have access too this is what I have found.
Campfire now seem to be "magical" instead of "humanoid".
Normal Aura now seem to be "construct" instead of "untargetable"
Shaman Idol now seem to be "magical" instead of "construct"
These changes move those three to their correct locations, and add race checks for anything relevant to hopefully narrow results. I left the Aura and other 3 items under "utnargetable" untouched just in case. Just like Rune remains under "construct".
I was unable to test the following:
Banner - Moved from "humanoid" to "magical" like campfire was?
Rune - …
> Campfire / Aura Semi Spawn Type Fix

- src/plugins/map/MQ2Map.cpp
- src/plugins/map/MQ2MapCommands.cpp
- Updates `/mapf` command to output correct radius value instead of just 0/1 for radius filters.
- Updates `/mapf xyzradius #` to store the `#` in the INI instead of just `0/1`.
- Updates plugin init to read the radius value from the INI instead of skipping it. The existing comment here about why these radius weren't being set on load kinda makes sense though...
Not sure if anything extra is needed for target or spell radius, just updated for camp and pull.
> Store radius values of mapfilters. Fixes #600

- src/main/MQ2Utilities.cpp
Another situation where an aura wasn't being categorized as such due to the EQ spawn type changes.
Related to #561
> Fix "Pact of the Wolf" Showing as Object not Aura

- src/main/MQ2Data.cpp
- src/main/MQ2DataAPI.cpp
- src/main/MQ2Utilities.cpp
- src/main/datatypes/MQ2AchievementType.cpp
- src/main/datatypes/MQ2BasicTypes.cpp
- src/main/datatypes/MQ2DataTypes.h
Added support for milliseconds, based on work started by @martinlindhe
- Added the following members to the time type: Milliseconds, MillisecondsSinceEpoch and MillisecondsSinceMidnight
- Set night time range to [7pm, 5am)
Times are represented as local time, otherwise we have to account for time zones.
> Implement `time` type using chrono and date

- src/main/MQ2ImGuiTools.cpp
- Corrected a typo in "Key Bindings" settings panel
> Typo fix in MQ2ImGuiTools

- src/plugins/eqbugfix/MQ2EQBugFix.cpp
Not exactly sure when this issue first appeared, but it only happens in the live client. Its our top crash by a large margin.
This is a bad condition that improperly casts a window pointer to another polymorphic type without checking
if it is safe. This results in reading memory beyond the end of the structure. In most cases this
goes unnoticed because there is more memory adjacent and it just reads junk. In rare cases this will
read beyond the end of a mapped page and trigger a segmentation fault. This patches the code to
remove the read.
To make things even more interesting, the reads are inconsequential - likely remnants of debug code.
Additionally, these reads are inside a __try block, giving the indication that somebody may have tried
to cover this case in a clumsy way. However note, …
> Implement workaround for eq bug involving CXWndManager::DestroyAllWindows

- include/moveitem.h
Fix PackFind to return correctly empty pack slot or inventory slot based on room for given item
> Fix PackFind to return correctly empty pack slot or inventory slot

- src/main/datatypes/MQ2AdvLootType.cpp
Updated to add FG attribute to the AdvLootType.
Can check if an Item is set to FG in the Personal/Shared Lists.
> Added FG to AdvLootType

- src/plugins/autologin/MQ2AutoLogin.cpp
- src/plugins/autologin/MQ2AutoLogin.h
Originally I was only exposing the hotkey, and saving it in the TLO class to a char array, and the TLO had only member HotKey.  The intent was to use it for things like /setwintitle, to see server, char, zone, hotkey, etc. to make clear while getting used to boxing groups, which char was on which hotkey.  Decided to just expose the additional data (other than password) via the TLO anyway.  The only imgui addition to the display for autologin I added was hotkey.
> Expose profile data for use in TLO AutoLogin, including hotkey.

- src/plugins/lua/bindings/lua_MQBindings.cpp
Adds the missing parity method to the Lua bindings as outlined in
https://github.com/macroquest/macroquest/issues/728
> adds getAllGroundItems to MQLua (issue 728)

- src/plugins/lua/LuaCommon.h
- src/plugins/lua/MQ2Lua.cpp
- src/plugins/lua/lua/mq/PackageMan.lua
- Prevents crashing when changing luajit versions
- Package Path now searches jitVersion folder first before falling back
- Package CPath now searches jitVersion folder (no fallback)
- Revert previous workaround for PackageMan now that issue has been fixed
- Add jitVersion path to PackageMan modules and URL for luarocks
> Add jit version to modules path

- src/plugins/lua/lua/mq/Set.lua
Adds a Set object that can be used as shown here.  Reduces the large and ugly tables necessary to accomplish this pattern.
```lua
local Set = require('mq.Set')
-- This is how I think a set of values should be created
local classes = Set.new({'Warrior', 'Enchanter', 'Cleric'})
-- To check against the set, we don't need to iterate because we use the underlying set data structure
if classes:contains('Warrior') then
print('Warrior needs food badly')
end
-- We can also check for various values at once
if classes:contains({'Warrior', 'Enchanter', 'Cleric'}) then
print('The MMO Trifecta is present')
end
-- We can also add and remove values from the set
classes:add('Rogue')
classes:remove('Cleric')
```
> Adds a Set object and methods to Lua helpers

- src/common/NamedPipes.cpp
From #780:
> This is based on the documentation for _ReadFile_ rather than _ReadFileEx_:
> https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile
> >If a named pipe is being read in message mode and the next message is longer than the nNumberOfBytesToRead parameter specifies, ReadFile returns FALSE and GetLastError returns ERROR_MORE_DATA. The remainder of the message can be read by a subsequent call to the ReadFile or PeekNamedPipe function.
> 
> ReadFileEx's documentation is silent on this.
This fixes the issue on Wine, but needs someone to test it on Windows.
> Fix #780 , handle ERROR_MORE_DATA

- src/main/datatypes/MQ2DataTypes.h
- src/main/datatypes/MQ2WindowType.cpp
Added new WindowType, InvSlotWindow with the following properties:
- Background
- ItemLocation
- ItemIndexSlot1
- ItemIndexSlot2
- ItemIndexSlot3
- Item
- ItemOffsetX
- ItemOffsetY
- ItemTexture
- Quantity
- Selected
- FindSelected
- HotButton
- InventorySlotLinked
- Text
- Mode
Usage:
mq.TLO.Window("BazaarWnd").Child(string.format("BZR_BazaarSlot0")).InvSlot.Selected()
> Added new WindowType, InvSlotWindow

- include/mq/base/String.h
- src/main/MQ2Globals.cpp
- src/main/MQ2Main.h
- src/main/MQ2Utilities.cpp
- src/main/datatypes/MQ2CharacterType.cpp
- Add remove_chars for removing specific characters in a string
- Deprecate szZoneExpansionName (and update for Laurion's Song)
- Update GetZoneExpansionX to use dbstr for expansions
- Update Alternate Currency Enums to match dbstr consistently
- Modify GetCurrencyIDByName to use dbstr for alt currencies -- this will allow for mq.TLO.Me.AltCurrency('<name>')() to work with the singular or plural name of the currency.  Additionally, it will match regardless of apostrophe or backtick to be compatible with previous changes
> Use dbstr for expansions and alt currencies

- include/mq/api/Abilities.h
- include/mq/base/String.h
- src/eqdata/skills.h
- src/main/MQ2Commands.cpp
- src/main/MQ2Globals.cpp
- src/main/MQ2Inlines.h
- src/main/MQ2Main.vcxproj
- src/main/MQ2Main.vcxproj.filters
- src/main/api/Abilities.cpp
- src/main/datatypes/MQ2CharacterType.cpp
- Move IsNumber to strings.h
- Update skills.h with innate skill names
- Update szInnates with appropriate data
- Split Ability functions into their own files and add documentation User Facing:
- /doability will now accept quoted or unquoted ability names
- /doability will now work for innate skills (Fixes #371)
- mq.TLO.Me.Ability is now a boolean. It returns true or false based on whether you have the ability.
- mq.TLO.Me.AbilityReady will no longer say an ability is ready if you don't have that ability.
- Added mq.TLO.Me.AbilityTimerTotal which will return the total amount of time an ability takes to refresh. This is only available while the ability is in cooldown, otherwise it returns 0. Useful for converting mq.TLO.Me.AbilityTimer into a percentage.  (Supersedes #823)
> Ability work

- contrib/imgui/imconfig.h
- include/mq/base/Color.h
- include/mq/imgui/Widgets.h
- src/main/ImGuiBackendDX11.cpp
- src/main/ImGuiManager.cpp
- src/main/ImGuiManager.h
- src/main/MQ2DeveloperTools.cpp
- src/main/MQ2FrameLimiter.cpp
- src/main/MQ2WindowInspector.cpp
- src/main/MQImguiWidgets.cpp
- src/plugins/lua/bindings/lua_ImGuiCustom.cpp
- src/plugins/lua/bindings/lua_ImGuiUserTypes.cpp
When your mouse cursor moves over an imgui window, any item/button/spell/etc attached to the cursor will continue to appear on the cursor, like magic.
> Add support for rendering the EQ cursor with ImGui

- src/loader/AutoLoginImGui.cpp
Adds back the "Load All" button to the profile group submenu instead of clicking on the profile group name in the list of profile groups.
> Add load all button instead of click profile parent

- src/plugins/lua/lua/examples/fish.lua
Updates the examples/lua.fish with:
Updated functions from function expression declaration to direct declarations
Removed use of mq.cmd.echo to output to the console, and replaced its use with print and printf
Removed use of mq.cmd.xxx commands and replaced them with the generally accepted mq.cmd('/command) syntax
> Updates examples/fish.lua

- src/plugins/lua/MQ2Lua.cpp
Fix applied to avoid a silent crash to desktop by ensuring selection.table is valid.
The crash would occur when pressing Lua Task Manager -> Launch Script -> OK button without selecting an existing file.
> Added nullptr check to avoid a silent crash to desktop

- src/main/MQCommandAPI.cpp
I noticed an issue with the /aa command referenced in issue #875 and tracked it down to the DoCommandF incorrectly passing the format string instead of the output string to the DoCommand function.
> Fix DoCommandf passing incorrect parameter to DoCommand

- src/main/MQ2Spells.cpp
Check positive or negative value for SPA 0 and 15 depending on `bIncrease` passed in.
```
> /echo ${Me.FindBuff[spa 0 and spa 15]}
Spiritual Ascendance
> /echo ${Me.FindBuff[detspa 0 and spa 15]}
Ancient: Allure of Extinction
```
> handle detspa vs spa for hp and mana

- src/main/ImGuiManager.cpp
- clarified when an mqoverlay is not suspended, that it can not be resumed. If you had stopped mqoverlay and then did a resume, it would say it was already running.
> Overlay writeout clarification

- src/main/MQPluginHandler.cpp
- fix issue where unloading a plugin with a shortened name did not update macroquest.ini
> Plugin Handler - fixes #888

- src/plugins/autologin/MQ2AutoLogin.cpp
- adds CustomCharacterINI to typemember
- - ex: mq.TLO.AutoLogin.Profile.CustomCharacterIni() and ${AutoLogin.Profile.CustomCharacterINI}
> Feat - add CustomCharacterINI to type member
