macroquest/macroquest

- src/loader/MacroQuest.cpp
- src/loader/resource.h
- Rename Gitlab to Github
- update MQ git link to github
- update MQ issue tracker link to github
> Update Loader links to github

- src/loader/MacroQuest.rc
- corrected menu item from gitlab to github
> Update .rc from gitlab to github

- src/plugins/map/MQ2MapCommands.cpp
Fix mapfilters accidentally falling into the radius filter handling
> use IsRadius instead of UsesRadius

- src/MacroQuest.sln
- src/main/MQ2AutoInventory.cpp
- src/main/MQ2Main.h
- src/main/MQ2PluginHandler.cpp
- src/plugins/autobank/MQ2AutoBank.cpp
- src/plugins/autobank/MQ2AutoBank.rc
- src/plugins/autobank/MQ2AutoBank.vcxproj
- src/plugins/autobank/MQ2AutoBank.vcxproj.filters
- src/plugins/autobank/README.md
- src/plugins/autobank/resource.h
Add gbAutoBankTrophiesWithTradeskill, ContextMenu_TrophysId, Add to switch, add relevant INI entries, Add option to context menu, apply filter if necessary.
> Autobank, add filter for tradeskill items with mods (Trophies)

- src/main/MQ2Commands.cpp
resolves #646 
- added "mq2data" to available filter output
> updated filter output

- src/plugins/lua/contrib/imgui/sol_ImGui.h
Added bindings for table column flag checks.
The sample code for context menu in table columns use these.
> Master add sol imgui bindings

- include/mq/base/GlobalBuffer.h
- src/main/MQ2DataAPI.cpp
- src/main/MQ2Globals.cpp
- src/main/MQ2Globals.h
- src/main/MQ2Main.vcxproj
- src/main/MQ2Main.vcxproj.filters
- src/main/datatypes/MQ2AchievementType.cpp
- src/main/datatypes/MQ2BasicTypes.cpp
- src/main/datatypes/MQ2CurrentZoneType.cpp
- src/main/datatypes/MQ2EverQuestType.cpp
- src/main/datatypes/MQ2ItemType.cpp
- src/main/datatypes/MQ2SpawnType.cpp
- src/main/datatypes/MQ2SpellType.cpp
- src/main/datatypes/MQ2WindowType.cpp
- src/main/datatypes/MQ2ZoneType.cpp
- src/plugins/lua/LuaThread.cpp
- src/plugins/lua/LuaThread.h
- src/plugins/lua/MQ2Lua.cpp
- Drop in replacement for DataTypeTemp in most cases
- Separates DataTypeTemp buffer between lua scripts
- Fixes #679
> Add SGlobalBuffer replacement for DataTypeTemp

- src/main/MQ2Inlines.h
- corrected inline bool return value from "0" to false
> Has Skill return value

- src/main/datatypes/MQ2MathType.cpp
Changed singular commas into comma or spaces and eats leading comma or spaces.
> Update MQ2MathType.cpp with comma and space for distance separation

- src/main/datatypes/MQ2DataTypes.h
- src/main/datatypes/MQ2GroundType.cpp
- src/plugins/lua/bindings/lua_MQBindings.cpp
Functionality was mentioned and wished for by CB
https://discord.com/channels/511690098136580097/866047684242309140/1100025397346836482
> Add a predicate search function for lua to find ground items

- src/main/MQ2Utilities.cpp
- added missing NoS for GetMaxCharacterLevel
> MQ2Utilities - GetMaxCharacterLevel

- data/resources/Zones.ini
- Added Laurion's Song zones to Zones.ini
> Zones.ini - Laurion's Song

- src/main/MQ2ImGuiConsole.cpp
- src/main/MQ2Main.vcxproj
- src/main/vcpkg_mq.txt
- Persistent logging between sessions (logged to SQLite)
- Should mostly handle multiple clients
- Not intended as an end user feature
> Add Dev Feature: Persistent commands

- src/plugins/lua/bindings/lua_ImGuiUserTypes.cpp
Add some missing ImDrawList bindings to enable things like <https://github.com/ocornut/imgui/issues/4719>
> Add ImDrawList Channels* bindings

- src/plugins/lua/lua/examples/luarocks.lua
Add an example script that covers using PackageMan.lua to load each of the available luarocks modules from the MQ luarocks server.
> add example for mq luarocks

- src/plugins/targetinfo/MQ2TargetInfoPHs.txt
That looks allot more like I originally wanted.
> Updated for LS (FelisMalum)

- include/mq/imgui/ConsoleWidget.h
- src/main/ImGuiZepEditor.cpp
- src/main/MQ2ImGuiConsole.cpp
- src/plugins/lua/bindings/lua_ImGuiCustom.cpp
ImGuiConsole has a new property called "opacity" that you can set on creation which will multiply all theme attributes with that alpha value.
> ImGuiConsole now works with clipping... don't ask.

- src/plugins/lua/bindings/lua_MQBindings.cpp
- String now correctly serailzes single backslash (\) characters
- numbers correctly serialize as double or int64
> Fixed lua bindings:

- src/plugins/lua/bindings/lua_MQBindings.cpp
Added support to serialize \n and \t
> Added more serialization support for newlines and tabs

- src/main/datatypes/MQ2TaskType.cpp
> ZoneID for Task Objectives

- src/main/MQ2Main.vcxproj
- src/main/MQ2Main.vcxproj.filters
- src/main/MQDataAPI.cpp
- src/main/datatypes/DataTypeList.h
- src/main/datatypes/MQ2DataTypes.cpp
- src/main/datatypes/MQ2DataTypes.h
- src/main/datatypes/MQSocialType.cpp
- Add new Social TLO to access social buttons.
Supports the following Members:
. Name
. Cmd(0-4)
. TimerBegin
. TimerDuration
. Color
> Social tlo added

- src/main/MQ2Main.vcxproj
small fix so emu can be built off latest mq
> add win32 to new MQSocialType.cpp

- contrib/imgui/imgui.cpp
- contrib/imgui/imgui.h
- src/main/ImGuiManager.cpp
This helps for ISBoxer users who use mini windows that causeis ImGui to reset window positions.
> Added an option for imgui to ignore its off-screen detection code.

- src/main/MQ2AutoInventory.cpp
- update mq2autoinventory "Destroy" button to handle skipping no destroy items
> Update MQ2AutoInventory to handle no destroy

- src/main/datatypes/MQ2CharacterType.cpp
- resolves #879
- pLocalPlayer->TimeStamp to pDisplay->TimeStamp
> timestamp fix

- src/main/datatypes/MQ2PetType.cpp
> SpellHold TLO info for pets

- data/resources/Zones.ini
Grabbed the names of the zones for expansion and found their related shortnames with Sic. Tested in Meshgen to ensure all zones would load and generate a mesh.
> add The Outer Brood to Zones.ini

- include/mq/base/Config.h
- src/loader/LoaderAutoLogin.cpp
- src/loader/ProcessList.cpp
- src/login/AutoLogin.cpp
- src/main/MQ2Internal.h
- src/main/MQ2Main.cpp
- src/main/MQ2Utilities.cpp
- src/main/MQCommands.cpp
- src/main/MQDetourAPI.cpp
- src/main/MQPluginHandler.cpp
- src/main/MQRenderDoc.cpp
- Cleaning up / optimizing a bunch of code paths related to process and dll names.
- Fix launcher so that eq doesn't run elevated if the launcher happens to be elevated.
- Dynamically load D3DPERF_BeginEvent etc since we don't usually need them.
> Improve process tracking
